<a href="https://colab.research.google.com/github/jimmy040527-prog/Always-Keep-Learning/blob/main/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Learning NumPy: NumPy 50 exercises and solution**


## Import required libraries

In [4]:
import numpy as np

import os


## Exercise 1. Import numpy as np and see the version¶

In [5]:
import numpy as np
print(np.__version__)

2.1.3


## Exercise 2. How to create a 1D array?

In [8]:
# Question : Create a 1D array of numbers from 0 to 9
# Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 3. How to create a boolean array?

In [11]:
# Question : Create a 3×3 numpy array of all True’s

# Solution

# if u use np.full, there's no need to write dtype=bool!!!

np.full((3, 3), True, dtype=bool)

# or
np.full((9), True, dtype=bool).reshape(3, 3)

# or
np.ones((3, 3), dtype=bool)

# or
np.ones((9), dtype=bool).reshape(3, 3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Exercise 4. How to extract items that satisfy a given condition from 1D array?

In [14]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

#Solution

arr = np.arange(10)
arr[arr%2 == 1]

# arr[condition] only extract elements satisfy condition


array([1, 3, 5, 7, 9])

## Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

In [20]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Solution

arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

# arr[condition] = value means change all the elements with value that satisfy the condition

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Exercise 6. How to replace items that satisfy a condition without affecting the original array?

In [23]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution

arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print(f"Modified Array: {out}")

print(f"\nOriginal Array: {arr}")


Modified Array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array: [0 1 2 3 4 5 6 7 8 9]


## Exercise 7. How to reshape an array?

In [27]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])

# Solution

arr = np.arange(10)

arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
# or
arr = np.arange(10)

arr.reshape(2, -1)

# -1 here means let NumPy calculate columns by itself


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Exercise 8. How to stack two arrays vertically?



In [36]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

np.vstack([a, b])  # List
np.vstack((a, b))  # Tuple

# [] and (), the output is the same

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Exercise 9. How to stack two arrays horizontally?

In [39]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


# Solution:

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a, b])
np.hstack((a, b)) # same

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Exercise 10. How to generate custom sequences in numpy without hardcoding?

In [43]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


# Solution

a = np.array([1, 2, 3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]
# np.r_: Concatenate arrays along the first axis

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
# or
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## Exercise 11. How to get the common items between two python numpy arrays?

In [49]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])

# Solution
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b, assume_unique=False, return_indices=False)


array([2, 4])

## Exercise 12. How to remove from one array those items that exist in another?

In [51]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])

# Solution
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

## Exercise 13. How to get the positions where elements of two arrays match?

In [52]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)


# Solution

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

## Exercise 14. How to extract all numbers between a given range from a numpy array?

In [54]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)


# Solution

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

## Exercise 15. How to make a python function that handles scalars to work on numpy arrays?

In [58]:
# Question: Convert the function maxx that works on two scalars, to work on two arrays.
# Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# maxx(1, 5)
#> 5

# Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# Solution

def pair_max(x, y):
  maximum = [maxx(a, b) for a, b in zip(x, y)]
  # zip() pairs elements at the same index into tuples.
  return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

## Exercise 16. How to swap two columns in a 2d numpy array?

In [62]:
# Question: Swap columns 1 and 2 in the array arr.

# Input:

arr = np.arange(9).reshape(3, 3)

print(f'Original array: {arr}')

# Solution

print(f"\nModified array: {arr[:, [1, 0, 2]]}")
# : means select all rows.
# 1 → Second column comes first.
# 0 → First column comes second.
# 2 → Third column stays last.

# Just remember, NumPy uses arr[rows, columns] !!!

Original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array: [[1 0 2]
 [4 3 5]
 [7 6 8]]


## Exercise 17. How to swap two rows in a 2d numpy array?

In [64]:
# Question: Swap rows 1 and 2 in the array arr:

# Input:

arr = np.arange(9).reshape(3,3)
print(f'Original array: {arr}')

# Solution

print(f"\nModified array: {arr[[1,0,2], :]}")


Original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array: [[3 4 5]
 [0 1 2]
 [6 7 8]]


## Exercise 18. How to reverse the rows of a 2D array?

In [65]:
# Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)
print(f'Original array: {arr}')

# Solution

print(f"\nModified array: {arr[::-1, :]}")

Original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array: [[6 7 8]
 [3 4 5]
 [0 1 2]]


## Exercise 19. How to reverse the columns of a 2D array?

In [67]:
# Question: Reverse the columns of a 2D array arr.

# Input: arr = np.arange(9).reshape(3,3)

# Solution

arr = np.arange(9).reshape(3, 3)
print(f'Original array: {arr}')

print(f"\nModified array: {arr[:, ::-1]}")

Original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array: [[2 1 0]
 [5 4 3]
 [8 7 6]]


## Exercise 20. How to create a 2D array containing random floats between 5 and 10?

In [68]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:

rand_arr = np.random.uniform(5, 10, size=(5, 3))

rand_arr

array([[9.19438919, 8.53979939, 9.76636938],
       [9.34919955, 7.93174468, 6.24666494],
       [9.26072379, 9.45149817, 9.2122667 ],
       [6.97550948, 9.68208766, 8.19566863],
       [8.05088752, 7.12479207, 6.47357649]])